import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        {
          hello.data ? 
             (
              <h1>
                {hello.data.greeting}
              </h1>
            )
             : 
          
             (
              <h1>
                hello.data
              </h1>
            )
            
        }

      </main>
    </>
  );
}