import Head from "next/head";
import { useEffect, useState } from "react";
import { api } from "~/utils/api";
import StockList, {Arz,  fetchArz} from "~/pages/api/arz/arz";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const [arzList, setJsonArray] = useState<Arz[]>([]);

  useEffect(() => {

    const fillData = async () => {
      const data: Arz[] = await  fetchArz();
      setJsonArray(data);
    }

    fillData();
    console.log(arzList);

  }, []); 

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <StockList />
      </main>
    </>
  );
}